name: CI

on:
  pull_request:
    branches: [ master ]
    types: [closed]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Docker-Compose
        run: docker-compose up -d --build
      
      - name: Run tests
        run: bash tests/site_up.sh
