name: CI

on:
  pull_request:
    branches: [ master ]
    types: [closed]

  push:
    branches: [ piepeline-upgrade ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Check current user
        run: whoami

      - name: List
        run: ls -lah ~

      - name: PWD
        run: pwd

      - name: Check out code
        uses: actions/checkout@v1

      - name: Check current user 2
        run: whoami

      - name: Switch user
        run: sudo su ubuntu

      - name: Check current user 3
        run: whoami

      - name: Branch
        run: git checkout piepeline-upgrade
      
      - name: Docker-Compose
        run: bash fun.sh
      
      - name: Run tests
        run: bash tests/site_up.sh

