name: CI

on:
  pull_request:
    branches: [ master ]
    types: [closed]

  push:
    branches: [ pipeline-upgrade ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Check current user
        run: whoami

      - name: List
        run: ls -lah

      - name: PWD
        run: pwd

      - name: Check out code
        uses: actions/checkout@v1

      - name: Branch
        run: git checkout pipeline-upgrade

      - name: Docker-Compose
        run: docker-compose up -d --build
      
      - name: Run tests
        run: bash tests/site_up.sh
